version: "2"
services:
  mysql:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress

  webpack:
    container_name: webpack
    build:
      context: webpack
    volumes:
      - /home/core/frontend:/work
    ports:
      - 30000:30000
  wp:
    container_name: wp
    image: wordpress:latest
    depends_on:
      - mysql
      - webpack
    links:
      - mysql
      - webpack
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: root
volumes:
  db_data:
